import { createHash, createPrivateKey, createPublicKey, sign } from 'node:crypto';
import { firmwareManifest } from '@/lib/firmware-manifest';

/** An SPKI-encoded ed25519 public key is this 12-byte prefix + the raw 32 bytes. */
const ED25519_SPKI_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');
/** PKCS#8 for an ed25519 private key is this 16-byte prefix + the 32-byte seed. */
const ED25519_PKCS8_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex');

function keyIdOf(spkiDer: Buffer): string {
  return `wf-${createHash('sha256').update(spkiDer).digest('hex').slice(0, 16)}`;
}
function cBytes(b: Buffer): string {
  return [...b].map((x) => `0x${x.toString(16).padStart(2, '0')}`).join(', ');
}

export function pubkeyHeader(pemText: string): string {
  const der = createPublicKey(pemText).export({ type: 'spki', format: 'der' }) as Buffer;
  if (der.length !== 44 || !der.subarray(0, 12).equals(ED25519_SPKI_PREFIX)) {
    throw new Error('not an ed25519 SPKI public key');
  }
  return [
    '// GENERATED by scripts/firmware-c-headers.ts from wifi-floppy/firmware/keys/*.pem.',
    '// Do not edit. src/lib/firmware-c-headers.test.ts fails if this drifts from the key.',
    '#ifndef FW_PUBKEY_H',
    '#define FW_PUBKEY_H',
    '#include <stdint.h>',
    `#define FW_PUBKEY_ID "${keyIdOf(der)}"`,
    `static const uint8_t FW_PUBKEY[32] = { ${cBytes(der.subarray(12))} };`,
    '#endif',
    '',
  ].join('\n');
}

/** A TEST-ONLY key. Never the release key: its seed is in the repository. */
export const FIXTURE_SEED_HEX = '0f'.repeat(32);

export function fixtureHeader(): string {
  const priv = createPrivateKey({
    key: Buffer.concat([ED25519_PKCS8_PREFIX, Buffer.from(FIXTURE_SEED_HEX, 'hex')]),
    format: 'der', type: 'pkcs8',
  });
  const der = createPublicKey(priv).export({ type: 'spki', format: 'der' }) as Buffer;
  const offer = { version: '1.2.0+gfixture', sequence: 7, sha256: 'ab'.repeat(32), sizeBytes: 533624 };
  const manifest = firmwareManifest(offer);
  const sig = sign(null, Buffer.from(manifest, 'ascii'), priv);   // ed25519 is deterministic
  return [
    '// GENERATED by scripts/firmware-c-headers.ts. A cross-implementation fixture:',
    '// signed by node:crypto over the manifest the SERVER builds, verified in C by',
    '// Monocypher over the manifest the FIRMWARE builds. Test key only.',
    '#ifndef FW_FIXTURE_H',
    '#define FW_FIXTURE_H',
    '#include <stdint.h>',
    `#define FIX_KEY_ID "${keyIdOf(der)}"`,
    `static const uint8_t FIX_PUBKEY[32] = { ${cBytes(der.subarray(12))} };`,
    `#define FIX_VERSION "${offer.version}"`,
    // No 'u' suffix (unlike a plain uint32_t literal would normally take):
    // test_fw_verify.c stringifies these via the preprocessor to embed them
    // in a JSON literal, and "7u" is not a valid JSON number. Both values
    // are small positive integers, so plain `int` literals are exact here.
    `#define FIX_SEQUENCE ${offer.sequence}`,
    `#define FIX_SHA256 "${offer.sha256}"`,
    `#define FIX_SIZE ${offer.sizeBytes}`,
    `#define FIX_SIGNATURE_B64 "${sig.toString('base64')}"`,
    `#define FIX_MANIFEST ${JSON.stringify(manifest)}`,
    '#endif',
    '',
  ].join('\n');
}
