#!/usr/bin/env bash
# Fetches five pinned CA root certificates and emits src/roots.h as a PEM
# string literal (plus tools/roots.pem, the flat bundle used to verify it).
#
# Why these five: the live chain for webadf.vercel.app today is
#   *.vercel.app -> Google Trust Services WR1 -> GTS Root R1
# GTS Root R1 alone would cover today's chain. The other four (ISRG Root X1,
# DigiCert Global Root G2, Amazon Root CA 1, GlobalSign Root CA) are pinned
# alongside it so a future CDN/CA change upstream of Vercel doesn't stall
# every device in the field waiting on a firmware update -- they're the CAs
# most commonly seen fronting large hosting platforms.
#
# This script does not verify anything by itself. After running it, verify
# the emitted bundle actually validates the live host (task-9-brief.md
# Step 1):
#   openssl s_client -connect webadf.vercel.app:443 -servername webadf.vercel.app \
#     -CAfile wifi-floppy/firmware/tools/roots.pem 2>&1 | grep "Verify return code"
# Expected: "Verify return code: 0 (ok)". If not, STOP -- do not commit a
# roots.h that fails this check.
set -euo pipefail
cd "$(dirname "$0")"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

fetch() {  # fetch <url> <outfile>
    curl -fsSL "$1" -o "$2"
}

# Canonical, operator-published PEM (or DER, converted below) downloads.
fetch https://pki.goog/repo/certs/gtsr1.pem                "$WORK/gts_root_r1.pem"
fetch https://letsencrypt.org/certs/isrgrootx1.pem          "$WORK/isrg_root_x1.pem"
fetch https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem "$WORK/digicert_global_root_g2.pem"
fetch https://www.amazontrust.com/repository/AmazonRootCA1.pem  "$WORK/amazon_root_ca1.pem"
fetch https://secure.globalsign.com/cacert/root-r1.crt      "$WORK/globalsign_root_ca.der"
openssl x509 -in "$WORK/globalsign_root_ca.der" -inform DER \
    -out "$WORK/globalsign_root_ca.pem" -outform PEM

# name:file, in the order they end up in roots.h/roots.pem.
CERTS=(
    "GTS Root R1:$WORK/gts_root_r1.pem"
    "ISRG Root X1:$WORK/isrg_root_x1.pem"
    "DigiCert Global Root G2:$WORK/digicert_global_root_g2.pem"
    "Amazon Root CA 1:$WORK/amazon_root_ca1.pem"
    "GlobalSign Root CA:$WORK/globalsign_root_ca.pem"
)

: > roots.pem
for entry in "${CERTS[@]}"; do
    file="${entry#*:}"
    subject="$(openssl x509 -in "$file" -noout -subject -nameopt oneline)"
    issuer="$(openssl x509 -in "$file" -noout -issuer -nameopt oneline)"
    if [ "$subject" != "${issuer/issuer=/subject=}" ]; then
        echo "gen_roots.sh: $file is not self-signed (subject != issuer) -- refusing to pin a non-root cert" >&2
        exit 1
    fi
    cat "$file" >> roots.pem
done

# Emit roots.h: a PEM string literal (adjacent per-line string constants,
# each with an explicit \n -- mbedtls_x509_crt_parse() wants LF-terminated
# PEM lines) plus each cert's SHA-256 fingerprint recorded in a comment so a
# future re-run's diff shows exactly what changed and why.
OUT=../src/roots.h
{
    echo "#ifndef ROOTS_H"
    echo "#define ROOTS_H"
    echo "// Generated by tools/gen_roots.sh -- do not hand-edit. Re-run that script to"
    echo "// refresh, then re-verify with the openssl check in task-9-brief.md Step 1"
    echo "// before committing: a bundle that cannot validate the live host is the"
    echo "// exact failure this file exists to prevent."
    echo "//"
    echo "// SHA-256 fingerprints at generation time:"
    for entry in "${CERTS[@]}"; do
        name="${entry%%:*}"
        file="${entry#*:}"
        fp="$(openssl x509 -in "$file" -noout -fingerprint -sha256 | cut -d= -f2)"
        printf '// %-26s %s\n' "$name:" "$fp"
    done
    echo "#include <stddef.h>"
    echo
    echo "static const char root_ca_pem[] ="
    for entry in "${CERTS[@]}"; do
        file="${entry#*:}"
        sed -e 's/\r$//' -e 's/.*/"&\\n"/' "$file"
    done
    echo ";"
    echo
    echo "// mbedtls_x509_crt_parse() (PEM path) scans for the NUL terminator, so the"
    echo "// length it wants is sizeof(root_ca_pem) (includes the NUL), not strlen()."
    echo "static const size_t root_ca_pem_len = sizeof(root_ca_pem);"
    echo
    echo "#endif"
} > "$OUT"

echo "Wrote $(cd "$(dirname "$OUT")" && pwd)/$(basename "$OUT") and $(pwd)/roots.pem" >&2
