// GENERATED by scripts/firmware-c-headers.ts. A cross-implementation fixture:
// signed by node:crypto over the manifest the SERVER builds, verified in C by
// Monocypher over the manifest the FIRMWARE builds. Test key only.
#ifndef FW_FIXTURE_H
#define FW_FIXTURE_H
#include <stdint.h>
#define FIX_KEY_ID "wf-7ba63121b6f977ed"
static const uint8_t FIX_PUBKEY[32] = { 0xd9, 0xbf, 0x21, 0x48, 0x74, 0x8a, 0x85, 0xc8, 0x9d, 0xa5, 0xaa, 0xd8, 0xee, 0x0b, 0x0f, 0xc2, 0xd1, 0x05, 0xfd, 0x39, 0xd4, 0x1a, 0x4c, 0x79, 0x65, 0x36, 0x35, 0x4f, 0x0a, 0xe2, 0x90, 0x0c };
#define FIX_VERSION "1.2.0+gfixture"
#define FIX_SEQUENCE 7
#define FIX_SHA256 "abababababababababababababababababababababababababababababababab"
#define FIX_SIZE 533624
#define FIX_SIGNATURE_B64 "9bYM4BXwDbu3VDFMSlFG90fGpR1EotMEyjQmSfpHDSbEG6Rn3jri/U/SsQpllLZQPVUvhP6ijzz4tZfsdSZ8Dg=="
#define FIX_MANIFEST "webadf-fw-v1\n1.2.0+gfixture\n7\nabababababababababababababababababababababababababababababababab\n533624"
#endif
