#!/usr/bin/env bash
# The version header is generated by a standalone CMake script precisely so
# that it can be tested here without configuring the whole firmware build.
set -euo pipefail
cd "$(dirname "$0")"
GEN="$(cd .. && pwd)/cmake/gen_version_header.cmake"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
fail=0
checks=0
check() { # check <description> <result>
  checks=$((checks + 1))
  if [ "$2" = "0" ]; then echo "  ok   - $1"; else echo "  FAIL - $1"; fail=1; fi
}

echo "test_version_header"

# A throwaway repo, so the test never depends on the state of the real one --
# in particular not on whether THIS tree happens to be dirty while it runs.
mkdir -p "$TMP/repo"
(
  cd "$TMP/repo"
  git init -q
  git config user.email t@t.test
  git config user.name t
  echo hello > f.txt
  git add f.txt
  git commit -qm first
)
SHORT="$(git -C "$TMP/repo" rev-parse --short HEAD)"

# 1. In a clean git work tree the suffix is +g<short-hash>.
cmake -DSEMVER=1.0.0 -DSRC_DIR="$TMP/repo" -DOUT="$TMP/v1.h" -P "$GEN" >/dev/null
grep -q "\"1.0.0+g${SHORT}\"" "$TMP/v1.h" && check "clean tree gets +g<hash>" 0 \
  || check "clean tree gets +g<hash>" 1

# 2. A dirty work tree is marked, because a build nobody can identify must
#    never be publishable.
echo changed >> "$TMP/repo/f.txt"
cmake -DSEMVER=1.0.0 -DSRC_DIR="$TMP/repo" -DOUT="$TMP/v2.h" -P "$GEN" >/dev/null
grep -q "\"1.0.0+g${SHORT}-dirty\"" "$TMP/v2.h" && check "dirty tree is marked -dirty" 0 \
  || check "dirty tree is marked -dirty" 1

# 3. No git at all still builds -- a firmware build must not require a VCS.
mkdir -p "$TMP/nogit"
cmake -DSEMVER=1.0.0 -DSRC_DIR="$TMP/nogit" -DOUT="$TMP/v3.h" -P "$GEN" >/dev/null
grep -q '"1.0.0+nogit"' "$TMP/v3.h" && check "a non-repo builds as +nogit" 0 \
  || check "a non-repo builds as +nogit" 1

# 4. The macro name is what main.c will include.
grep -q "#define WF_FIRMWARE_VERSION" "$TMP/v3.h" && check "defines WF_FIRMWARE_VERSION" 0 \
  || check "defines WF_FIRMWARE_VERSION" 1

# 5. Rewriting with an unchanged value must not touch the file's mtime, or
#    every build relinks the whole image.
BEFORE=$(stat -f %m "$TMP/v3.h")
sleep 1
cmake -DSEMVER=1.0.0 -DSRC_DIR="$TMP/nogit" -DOUT="$TMP/v3.h" -P "$GEN" >/dev/null
AFTER=$(stat -f %m "$TMP/v3.h")
[ "$BEFORE" = "$AFTER" ] && check "an unchanged value does not rewrite the file" 0 \
  || check "an unchanged value does not rewrite the file" 1

# 6. A changed value DOES rewrite it -- the mtime guard above must not be so
#    eager that a real version bump fails to reach the compiler.
cmake -DSEMVER=1.2.3 -DSRC_DIR="$TMP/nogit" -DOUT="$TMP/v3.h" -P "$GEN" >/dev/null
grep -q '"1.2.3+nogit"' "$TMP/v3.h" && check "a changed value is written" 0 \
  || check "a changed value is written" 1

echo "  ${checks} checks"
exit $fail
