// Pins floppy.pio's drive_id PROGRAM (not just the model in drive_id.c) to
// what bus_out.c assumes about it (HD spec §5.4, final-fix F5), and the two
// load words bus_out.c writes into it (drive_id_load, drive_id.h).
//
// drive_id.c/test_drive_id.c model the PROTOCOL: what the answer looks like,
// select by select. Neither one looks at the actual PIO instruction words,
// so a hand-edit of floppy.pio's drive_id program that kept the protocol but
// moved reset_load/repeat_load/on_selected_wait, or changed what "the ID
// load" assembles to, would pass every test there while silently breaking
// bus_out.c, which pokes drive_id_load()'s raw words straight into
// instr_mem[drive_id_offset_reset_load] and [drive_id_offset_repeat_load],
// and compares the machine's PC against drive_id_offset_on_selected_wait.
//
// THE 1.4.0 BUG this pins (HANDOFF §3an, FIXED 2026-09-27): pico-sdk 2.3.0's
// pio_encode_mov(pio_osr, src) in a release build returns `mov pindirs, src`
// -- with PARAM_ASSERTIONS off the _PIO_INVALID_* flags are 0, so pio_osr ==
// pio_exec (7), which pio_encode_mov remaps to pio_exec_mov (4) == pio_pindirs,
// which it remaps again to pio_pindirs_mov (3). Measured on the board:
// pio_encode_mov(pio_osr, pio_null) == 0xa063. So every HD reload turned
// RDY's output enable off. drive_id_load() builds the word from the fields.
//
// bus_out.c itself is device-only (it holds PIO/spinlock register state) and
// is excluded from the host build (test/run.sh), so it cannot be linked here
// and exercised directly. Checks instead:
//
//  1. drive_id_load() gives the exact words, and each decodes as a MOV whose
//     destination is OSR.
//  2. The golden array below is drive_id_program_instructions[] as pioasm
//     emits it (wifi-floppy/firmware/build/floppy.pio.h, generated by
//     `pico_generate_pio_header` during `pnpm firmware:build`), plus the
//     offset #defines from the same file. Regenerate it by running
//     `pnpm firmware:build` and copying build/floppy.pio.h's
//     drive_id_program_instructions[] and drive_id_offset_* here.
//  3. If that generated header is present on disk right now (a prior build
//     was run in this tree), this test reads it as TEXT -- not #include, as
//     the header pulls in hardware/pio.h, which needs the pico-sdk on the
//     include path -- and compares every word live.
//
// Changing the PIO requires changing drive_id.c's model and
// test_drive_id.c in the same commit -- and this golden array too.
#include "harness.h"
#include "../src/drive_id.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define DRIVE_ID_PROGRAM_LEN 15

// drive_id_program_instructions[], as pioasm emits it.
static const uint16_t golden[DRIVE_ID_PROGRAM_LEN] = {
    0xa003, //  0: mov    pins, null              <- on_released
    0x2720, //  1: wait   0 pin, 0               [7]
    0x00c6, //  2: jmp    pin, 6
    0xa001, //  3: mov    pins, x                 (on_selected)
    0x20a0, //  4: wait   1 pin, 0                <- on_selected_wait
    0x0000, //  5: jmp    0
    0xa0e2, //  6: mov    osr, y                  <- reset_load
    0x6001, //  7: out    pins, 1                 (id_bit)
    0x20a0, //  8: wait   1 pin, 0
    0xa003, //  9: mov    pins, null
    0x00ec, // 10: jmp    !osre, 12
    0xa0e2, // 11: mov    osr, y                  <- repeat_load
    0x2720, // 12: wait   0 pin, 0               [7]   (off_wait)
    0x00c7, // 13: jmp    pin, 7
    0x0003, // 14: jmp    3
};
#define DRIVE_ID_OFFSET_ON_RELEASED      0
#define DRIVE_ID_OFFSET_ON_SELECTED_WAIT 4
#define DRIVE_ID_OFFSET_RESET_LOAD       6
#define DRIVE_ID_OFFSET_REPEAT_LOAD      11

// The two words bus_out.c writes, named so a change is visible by name.
#define DRIVE_ID_LOAD_HD  0xa0e2u   // mov osr, y      (Y holds DRIVE_ID_HD from init)
#define DRIVE_ID_LOAD_DD  0xa0ebu   // mov osr, ~null  (all ones)
#define DRIVE_ID_LOAD_NONE 0xa0e3u  // mov osr, null   (all zeros: "no drive")

// The RP2040/RP2350 PIO MOV fields, from the datasheet's layout:
//   [15:13] opcode (MOV = 101)   [12:8] delay/side-set
//   [7:5]   destination (OSR = 111; 011 = PINDIRS on RP2350)
//   [4:3]   op (00 none, 01 invert)   [2:0] source (Y = 010, NULL = 011)
static unsigned mov_opcode(uint16_t w) { return (w >> 13) & 7u; }
static unsigned mov_dest(uint16_t w)   { return (w >> 5) & 7u; }
static unsigned mov_op(uint16_t w)     { return (w >> 3) & 3u; }
static unsigned mov_src(uint16_t w)    { return w & 7u; }

static void the_load_words_are_mov_osr(void) {
    CHECK_EQ_INT(drive_id_load(true),  DRIVE_ID_LOAD_HD);
    CHECK_EQ_INT(drive_id_load(false), DRIVE_ID_LOAD_DD);
    CHECK_EQ_INT(drive_id_load_kind(DRIVE_ID_KIND_NONE), DRIVE_ID_LOAD_NONE);
    CHECK_EQ_INT(drive_id_load_kind(DRIVE_ID_KIND_DD), drive_id_load(false));
    CHECK_EQ_INT(drive_id_load_kind(DRIVE_ID_KIND_HD), drive_id_load(true));
    const drive_id_kind_t kinds[] = { DRIVE_ID_KIND_HD, DRIVE_ID_KIND_DD, DRIVE_ID_KIND_NONE };
    for (unsigned k = 0; k < 3; k++) {
        const uint16_t w = drive_id_load_kind(kinds[k]);
        CHECK_EQ_INT(mov_opcode(w), 5u);       // MOV
        CHECK_EQ_INT(mov_dest(w), 7u);         // OSR -- NOT pindirs (3), the 1.4.0 bug
        CHECK_EQ_INT((w >> 8) & 0x1fu, 0u);    // no delay
    }
    CHECK_EQ_INT(mov_op(drive_id_load(true)), 0u);
    CHECK_EQ_INT(mov_src(drive_id_load(true)), 2u);    // Y
    CHECK_EQ_INT(mov_op(drive_id_load(false)), 1u);    // invert
    CHECK_EQ_INT(mov_src(drive_id_load(false)), 3u);   // NULL
    CHECK_EQ_INT(mov_op(drive_id_load_kind(DRIVE_ID_KIND_NONE)), 0u);    // no invert
    CHECK_EQ_INT(mov_src(drive_id_load_kind(DRIVE_ID_KIND_NONE)), 3u);   // NULL
    // The .pio source's own default at both loads is HD's word.
    CHECK_EQ_INT(golden[DRIVE_ID_OFFSET_RESET_LOAD], DRIVE_ID_LOAD_HD);
    CHECK_EQ_INT(golden[DRIVE_ID_OFFSET_REPEAT_LOAD], DRIVE_ID_LOAD_HD);
}

static void the_program_fits_pio0(void) {
    // pio0 holds flux_out (7) + flux_in (7) + drive_id: 32 slots.
    CHECK(7 + 7 + DRIVE_ID_PROGRAM_LEN <= 32, "pio0 instruction memory");
    // on_selected_wait is the `wait 1 pin 0` bus_out.c checks the PC against.
    CHECK_EQ_INT(golden[DRIVE_ID_OFFSET_ON_SELECTED_WAIT], 0x20a0u);
}

// The select is a parameter (in_base), not GP2: no WAIT may name a GPIO by
// number. WAIT = opcode 001; source [6:5]: 00 GPIO, 01 PIN, 10 IRQ, 11 JMPPIN.
static void no_wait_names_a_gpio(void) {
    unsigned waits = 0;
    for (unsigned i = 0; i < DRIVE_ID_PROGRAM_LEN; i++) {
        if ((golden[i] >> 13) != 1u) continue;
        waits++;
        CHECK_EQ_INT((golden[i] >> 5) & 3u, 1u);      // PIN, relative to in_base
        CHECK_EQ_INT(golden[i] & 0x1fu, 0u);          // pin 0 = this drive's select
    }
    CHECK_EQ_INT(waits, 4u);
}

// Read build/floppy.pio.h as text and compare drive_id's words and offsets
// with golden[] above. Present only after a device build has run in this
// tree (build/ is gitignored), so its absence is reported, not failed.
static void the_generated_header_matches_the_golden_array_when_present(void) {
    FILE *f = fopen("../build/floppy.pio.h", "r");
    if (!f) {
        printf("  (skip: ../build/floppy.pio.h not present -- run `pnpm firmware:build` first "
               "to check live, not just against the golden array)\n");
        return;
    }
    char line[256];
    int on_released = -1, on_selected_wait = -1, reset_load = -1, repeat_load = -1;
    uint16_t got[32];
    int got_count = 0;
    int in_array = 0;
    while (fgets(line, sizeof(line), f)) {
        if (strstr(line, "#define drive_id_offset_on_released ")) sscanf(line, "%*s %*s %d", &on_released);
        if (strstr(line, "#define drive_id_offset_on_selected_wait ")) sscanf(line, "%*s %*s %d", &on_selected_wait);
        if (strstr(line, "#define drive_id_offset_reset_load ")) sscanf(line, "%*s %*s %d", &reset_load);
        if (strstr(line, "#define drive_id_offset_repeat_load ")) sscanf(line, "%*s %*s %d", &repeat_load);
        if (strstr(line, "drive_id_program_instructions[] = {")) { in_array = 1; continue; }
        if (in_array) {
            if (strstr(line, "};")) { in_array = 0; continue; }
            unsigned word;
            // Lines are either "    0xNNNN, // ..." or a bare ".wrap_target"/
            // ".wrap" comment line with no leading hex -- skip those.
            char *p = line;
            while (*p == ' ') p++;
            if (sscanf(p, "0x%x,", &word) == 1 && got_count < 32) got[got_count++] = (uint16_t)word;
        }
    }
    fclose(f);

    CHECK_EQ_INT(got_count, DRIVE_ID_PROGRAM_LEN);
    CHECK_EQ_INT(on_released, DRIVE_ID_OFFSET_ON_RELEASED);
    CHECK_EQ_INT(on_selected_wait, DRIVE_ID_OFFSET_ON_SELECTED_WAIT);
    CHECK_EQ_INT(reset_load, DRIVE_ID_OFFSET_RESET_LOAD);
    CHECK_EQ_INT(repeat_load, DRIVE_ID_OFFSET_REPEAT_LOAD);
    for (int i = 0; i < got_count && i < DRIVE_ID_PROGRAM_LEN; i++) CHECK_EQ_INT(got[i], golden[i]);
}

int main(void) {
    RUN(the_load_words_are_mov_osr);
    RUN(the_program_fits_pio0);
    RUN(no_wait_names_a_gpio);
    RUN(the_generated_header_matches_the_golden_array_when_present);
    return REPORT();
}
