# Generates the firmware version header. Run with `cmake -P`, never included.
#
# Standalone so that it is testable without configuring the firmware build,
# and so that it can run as a BUILD step rather than a CONFIGURE step. That
# distinction is the whole point: generating at configure time means switching
# commits keeps the old hash until someone re-runs CMake, which is the same
# class of bug -- a version that does not change when the image does -- that
# this file exists to remove.
#
# Required: -DSEMVER=<x.y.z> -DSRC_DIR=<git work tree> -DOUT=<header path>

if (NOT DEFINED SEMVER OR NOT DEFINED SRC_DIR OR NOT DEFINED OUT)
  message(FATAL_ERROR "gen_version_header: SEMVER, SRC_DIR and OUT are all required")
endif ()

set(_suffix "+nogit")
find_package(Git QUIET)
if (GIT_FOUND)
  # `-- .` scopes this to the firmware subtree. Without the pathspec, git
  # reports the LAST COMMIT OF THE WHOLE REPO, so a commit touching only the
  # Next.js app would produce a new firmware version for a byte-identical
  # image -- every board would read "1 release behind" for a change that never
  # touched firmware. WORKING_DIRECTORY alone does not scope anything.
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" log -1 --format=%h -- .
    WORKING_DIRECTORY "${SRC_DIR}"
    OUTPUT_VARIABLE _hash OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET RESULT_VARIABLE _hash_rc)
  if (_hash_rc EQUAL 0 AND _hash)
    # --porcelain prints one line per changed path and nothing at all when the
    # tree is clean, so emptiness IS the cleanliness test -- but it is
    # REPO-WIDE unless given a pathspec, whatever WORKING_DIRECTORY says. `-- .`
    # scopes it to the firmware sources that actually went into the image, so
    # an uncommitted change under src/ or a stray scratch file at the repo root
    # can no longer stamp a spotless firmware tree as -dirty and make it
    # unpublishable. Chasing those one at a time through .gitignore was the
    # wrong fix for an unbounded class.
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" status --porcelain -- .
      WORKING_DIRECTORY "${SRC_DIR}"
      OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET RESULT_VARIABLE _dirty_rc)
    if (_dirty_rc EQUAL 0 AND _dirty STREQUAL "")
      set(_suffix "+g${_hash}")
    else ()
      set(_suffix "+g${_hash}-dirty")
    endif ()
  endif ()
endif ()

set(_version "${SEMVER}${_suffix}")
set(_body "/* Generated by cmake/gen_version_header.cmake -- do not edit, do not commit. */\n")
string(APPEND _body "#ifndef WF_FIRMWARE_VERSION_H\n#define WF_FIRMWARE_VERSION_H\n")
string(APPEND _body "#define WF_FIRMWARE_VERSION \"${_version}\"\n")
string(APPEND _body "#endif\n")

# Write only on change. An unconditional file(WRITE) updates the mtime on
# every build, which would relink the whole image every time regardless of
# whether anything about the version actually moved.
set(_existing "")
if (EXISTS "${OUT}")
  file(READ "${OUT}" _existing)
endif ()
if (NOT _existing STREQUAL _body)
  file(WRITE "${OUT}" "${_body}")
  message(STATUS "firmware version: ${_version}")
endif ()
